ros__parameters:

  target_frame: camera_link
  transformation_tolerance: 0.01
  min_height: 0.0
  max_height: 1.0
  angle_min: -1.57
  angle_max: 1.57
  scan_time: 0.1
  range_min: 0.1
  range_max: 100
{'range_min': 0.1},{'range_max': 100}